version: 2

jobs:
  build:
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - add_ssh_keys:
                            fingerprints:
                                - 'c0:b6:0a:00:a2:14:04:be:69:80:67:59:64:8f:d7:46'
                      - run: npm install
    deploy:
        machine:
            enabled: true
        steps:
            - run:
                  name: Deploy Over SSH
                  command: |
                      ssh $SSH_USER@$SSH_HOST "git clone git@github.com:LajnaLegenden/PalmeusJS.git; cd PalmeusJS;npm run deploy"

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                  requires:
                      - build # only deploy once build job has completed
                  #  filters:
                  #  branches:
                  #      only: master # only deploy on the master branch
