version: 2.1
orbs:
    node: circleci/node@1.1.6

jobs:
  deploy:
    machine:
        enabled: true
    steps:
        - run:
            name: Deploy Over SSH
                command: |
                    ssh $SSH_USER@$SSH_HOST "git clone git@github.com:LajnaLegenden/PalmeusJS.git; cd PalmeusJS;npm run deploy"

workflows:
   version: 2
   build-and-deploy:
    jobs:
        - deploy
